core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^user/', include('registration.backends.simple.urls')),
    url(r'^user/', include('django.contrib.auth.urls')),
    url(r'^trip/create/$', login_required(TripCreateView.as_view()), name='trip_create'),
    url(r'trip/$', login_required(TripListView.as_view()), name='trip_list'),
    url(r'^trip/(?P<pk>\d+)/$', login_required(TripDetailView.as_view()), name='trip_detail'),
    url(r'^trip/update/(?P<pk>\d+)/$', login_required(TripUpdateView.as_view()), name='trip_update'),
    url(r'^trip/delete/(?P<pk>\d+)/$', login_required(TripDeleteView.as_view()), name='trip_delete'),
    url(r'^trip/(?P<pk>\d+)/comment/create/$', login_required(CommentCreateView.as_view()), name='comment_create'),
    url(r'^trip/(?P<trip_pk>\d+)/comment/update/(?P<comment_pk>\d+)/$', login_required(CommentUpdateView.as_view()), name='comment_update'),
    url(r'^trip/(?P<trip_pk>\d+)/comment/delete/(?P<comment_pk>\d+)/$', login_required(CommentDeleteView.as_view()), name='comment_delete'),
    url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
    url(r'^user/(?P<slug>\w+)/$', login_required(UserDetailView.as_view()), name='user_detail'),
    url(r'^user/update/(?P<slug>\w+)/$', login_required(UserUpdateView.as_view()), name='user_update'),
    url(r'^user/delete/(?P<slug>\w+)/$', login_required(UserDeleteView.as_view()), name='user_delete'),
    url(r'^search/$', login_required(SearchTripListView.as_view()), name='search'),
)

qu_abroad/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

RATING_CHOICES = (
(0, 'None'),
(1, '*'),
(2, '**'),
(3, '***'),
(4, '****'),
(5, '*****'),
)

# Create your models here.
class Trip(models.Model):
  title = models.CharField(max_length=1000)
  description = models.TextField(null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(User)

  def __unicode__(self):
    return self.title

  def get_absolute_url(self):
      return reverse("trip_detail", args=[self.id])


class Comment(models.Model):
    trip = models.ForeignKey(Trip)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(choices=RATING_CHOICES, default=0)

    def __unicode__(self):
        return self.text

class Vote(models.Model):
    user = models.ForeignKey(User)
    trip = models.ForeignKey(Trip, blank=True, null=True)
    comment = models.ForeignKey(Comment, blank=True, null=True)

    def __unicode__(self):
        return "%s upvoted" % (self.user.username)

templates/trip/trip_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p class="lead">Are you sure you want to delete "{{ trip.title }}"?</p>
<form method="post" action="">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/trip/trip_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ trip.title }}</h1>

{% if rating.rating__avg < 0.5 %}
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 1.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 2.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 3.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% elif rating.rating__avg < 4.5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ rating.rating__avg }})
{% else %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  ({{ rating.rating__avg }})
{% endif %}

<p>{{ trip.description }}</p>
<p>Posted by <a href="{% url 'user_detail' slug=trip.user.username %}">{{ trip.user.username }}</a> on {{ trip.created_at }}</p>
{% if trip.user == user %}
<p><a href="{% url 'trip_update' pk=trip.id %}">Edit trip</a></p>
{% endif %}
{% if comments.count > 0 %}
<h3>{{ comments.count }} Comment{{ comments.count|pluralize }}:</h3>
{% endif %}
{% for comment in comments %}
<div class="panel">
    <p>{{ comment.text }}</p>
    {% if comment.user == user %}
    <p><a href="{% url 'comment_update' trip_pk=trip.id comment_pk=comment.id %}">Edit comment</a></p>
    <p><a href="{% url 'comment_delete' trip_pk=trip.id comment_pk=comment.id %}">Delete comment</a></p>
    {% endif %}
    <p>Comment by <a href="{% url 'user_detail' slug=comment.user.username %}">{{ comment.user.username }}</a> on {{ comment.created_at }} ({{ comment.vote_set.all.count }} Vote{{ comment.vote_set.all.count|pluralize }})</p>
    <form method="post" action="{% url 'vote' %}">
        {% csrf_token %}
        <input type="hidden" name="comment" value="{{ comment.id }}" />
        <input type="hidden" name="trip" value="{{ trip.id }}" />
        <input type="hidden" name="user" value="{{ user.id }}" />
        <button>+</button>
    </form>
</div>
{% endfor %}
<p><a href="{% url 'comment_create' pk=trip.id %}">Write comment</a></p>
{% endblock %}

templates/trip/trip_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
<div class="col-lg-6">
<form method="post" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn-primary">Submit</button>
</form>
</div>
</div>
{% endblock %}

templates/trip/trip_list.html
{% extends 'base.html' %}
{% block content %}
{% for trip in object_list %}
<div class="panel">
    <h3><a href="{{ trip.get_absolute_url }}">{{ trip.title }}</a></h3>
    <p>Posted by <a href="{% url 'user_detail' slug=trip.user.username %}">{{ trip.user.username }}</a> on {{ trip.created_at }}</p>
    <p>{{ trip.vote_set.all.count }} Vote{{ trip.vote_set.all.count|pluralize }}</p>
    <form method="post" action="{% url 'vote' %}">
        {% csrf_token %}
        <input type="hidden" name="trip" value="{{ trip.id }}" />
        <input type="hidden" name="user" value="{{ user.id }}" />
        <button>+</button>
    </form>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if is_paginated %}
<nav>
    <ul class="pager">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}